<Project Sdk="Microsoft.NET.Sdk">
    <Import Project="../../Itinero.Common.props" />

    <PropertyGroup>
      <TargetFramework>net10.0</TargetFramework>
        <AssemblyName>Itinero.Geo</AssemblyName>
        <LangVersion>default</LangVersion>
        <PackageId>Itinero.Geo</PackageId>
    </PropertyGroup>

    <ItemGroup>
      <PackageReference Include="NetTopologySuite.Features" Version="2.1.0" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\Itinero\Itinero.csproj" />
    </ItemGroup>

</Project>
