<Project Sdk="Microsoft.NET.Sdk">
    <Import Project="../../Itinero.Common.props" />

    <PropertyGroup>
      <TargetFramework>net10.0</TargetFramework>
        <AssemblyName>Itinero.Profiles.Lua</AssemblyName>
        <LangVersion>latest</LangVersion>
        <PackageId>Itinero.Profiles.Lua</PackageId>
        <PackageTags>osm, openstreetmap, routing, mapping</PackageTags>
        <GeneratePackageOnBuild>false</GeneratePackageOnBuild>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <PackageReference Include="MoonSharp" Version="2.0.0" />
    </ItemGroup>

    <ItemGroup>
      <None Remove="Osm\*.lua" />
      <EmbeddedResource Include="Osm\*.lua" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\Itinero\Itinero.csproj" />
    </ItemGroup>

</Project>
