<Project Sdk="Microsoft.NET.Sdk">
  <Import Project="../../Itinero.Common.props" />

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <AssemblyName>Itinero</AssemblyName>
    <LangVersion>default</LangVersion>
    <PackageId>Itinero</PackageId>    
    <GeneratePackageOnBuild>false</GeneratePackageOnBuild>
    <Nullable>enable</Nullable>
    <PackageTags>osm, openstreetmap, routing, mapping</PackageTags>
  </PropertyGroup>
  <ItemGroup>
  </ItemGroup>
</Project>