<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <LangVersion>default</LangVersion>
    <Nullable>enable</Nullable>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="BenchmarkDotNet" Version="0.14.0" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\src\Itinero.IO.Osm\Itinero.IO.Osm.csproj" />
    <ProjectReference Include="..\..\src\Itinero.Profiles.Lua\Itinero.Profiles.Lua.csproj" />
    <ProjectReference Include="..\..\src\Itinero\Itinero.csproj" />
  </ItemGroup>
</Project>
