<Project Sdk="Microsoft.NET.Sdk">
    <Import Project="../../Itinero.Common.props" />

    <PropertyGroup>
      <TargetFramework>net10.0</TargetFramework>
        <AssemblyName>Itinero.Instructions</AssemblyName>
        <LangVersion>default</LangVersion>
        <PackageId>Itinero.Instructions</PackageId>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\Itinero\Itinero.csproj" />
    </ItemGroup>

    <ItemGroup>
      <EmbeddedResource Include="Configuration\default.json" />
    </ItemGroup>

</Project>
