name: .NET Core

on:
  push:
    branches: [ develop ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Checkout submodules
      uses: srt32/git-actions@v0.0.3
      with:
        args: git submodule update --init --recursive
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.301
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore
    - name: Test
      run: dotnet test --no-restore --verbosity normal --collect:"XPlat Code Coverage" --settings coverlet.runsettings
      working-directory: ./test/Itinero.Tests/
    - name: Extract branch name
      shell: bash
      run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
      id: extract_branch
    - uses: actions/checkout@v2
      with:
        ref: 'docs/coverage'
        path: 'coverages'
    - run: mkdir ./coverages/${{ steps.extract_branch.outputs.branch }}/
    - run: rsync -avm --include='*.xml' -f 'hide,! */' ./test/Itinero.Tests/TestResults ./coverages/${{ steps.extract_branch.outputs.branch }}/
    - name: Commit badge
      run: cd coverages && git config --local user.email "action@github.com" && git config --local user.name "GitHub Action" 
    - name: Commit badge
      run: cd coverages && git stage -A && git commit -m "Added new coverage results for ${{ steps.extract_branch.outputs.branch }}"
