name: .NET Core

on:
  push:
    branches: [ develop ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: 'true'
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.301
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore
    - name: Test
      run: dotnet test --no-restore --collect:"XPlat Code Coverage" --settings coverlet.runsettings
      working-directory: ./test/Itinero.Tests/
    - name: Extract branch name
      shell: bash
      run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
      id: extract_branch
    - run: mkdir ./${{ steps.extract_branch.outputs.branch }}/
    - run: rsync -avm --include='*.xml' -f 'hide,! */' ./test/Itinero.Tests/TestResults/ ./${{ steps.extract_branch.outputs.branch }}/
    - uses: actions/checkout@v2
      with:
        ref: 'docs/coverage'
        clean: 'false'
    - name: ReportGenerator
      uses: danielpalme/ReportGenerator-GitHub-Action@4.8.2
      with:
        reports: '${{ steps.extract_branch.outputs.branch }}/**/*.xml' 
        targetdir: '${{ steps.extract_branch.outputs.branch }}-new' 
        reporttypes: 'Html;' 
        assemblyfilters: '-protobuf-net' 
        verbosity: 'Info' 
        title: '' 
        tag: '${{ github.run_number }}_${{ github.run_id }}' 
    - run: rsync -avm ./${{ steps.extract_branch.outputs.branch }}-new/ ./${{ steps.extract_branch.outputs.branch }}/
    - run: rm -r ${{ steps.extract_branch.outputs.branch }}-new/
    - run: rm -r src/Itinero.IO.Osm.Tiles/ontology
    - run: rm -r test/Itinero.Tests/TestResults/
    - name: Commit badge
      run: git config --local user.email "action@github.com" && git config --local user.name "GitHub Action" 
    - name: Commit badge
      run: git stage -A && git commit -m "Added new coverage results for ${{ steps.extract_branch.outputs.branch }}"
    - name: Push badge commit
      uses: ad-m/github-push-action@master
      if: ${{ success() }}
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: 'docs/coverage'