name: Rebuild Coverage Docs

on:
  push:
    branches: [ 'docs/coverage' ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core # Required to execute ReportGenerator
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.101
    - name: ReportGenerator
      uses: danielpalme/ReportGenerator-GitHub-Action@4.8.2
      with:
        reports: 'develop/**/*.xml' 
        targetdir: 'develop' 
        reporttypes: 'Html;' 
        assemblyfilters: '-protobuf-net' 
        verbosity: 'Info' 
        title: '' 
        tag: '${{ github.run_number }}_${{ github.run_id }}' 
    - name: Commit badge
      run: git config --local user.email "action@github.com" && git config --local user.name "GitHub Action" 
    - name: Commit badge
      run: git stage -A && git commit -m "Added new coverage report."
    - name: Push badge commit
      uses: ad-m/github-push-action@master
      if: ${{ success() }}
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: 'docs/coverage'        